- name: Run kubectl command
  hosts: all
  tasks:
    - name: create new deployment
      ansible.builtin.command:
        cmd: kubectl apply -f /home/ubuntu/Deployment.yml
      become: yes
    - name: create new service
      ansible.builtin.command:
        cmd: kubectl apply -f /home/ubuntu/Service.yml
      become: yes  